### ISSUE TITLE
Recommend hashtags for image

### ISSUE THREAD

**Issue by kaustubhhiware** [CoolDogee/cap-that-pic#69]
Simply return extracted tags, and related tags from backend.

**Comment by kewsky** [comment]
We already have GetTagsFromImage function. Is all I need to do is add a endpoint for that?

**Comment by kewsky** [comment]
> Simply return extracted tags, and related tags from backend.

We already have GetTagsFromImage function. Is all I need to do is add a endpoint for that?

**Comment by kaustubhhiware** [comment]
I meant, when getCaptions is called, along with a list of caption objects, the backend should also send a list of strings corresponding to the tags for that image. 

I guess this isn't possible to implement immediately, I'll assign this to @asquare100 then.

**Comment by kaustubhhiware** [comment]
Closed via #100
